PermitRootLogin yes                                                                                                     
PasswordAuthentication no                                                                                               
UseDNS no                                                                                                               
HostKeyAlgorithms +ssh-rsa                                                                                              
PubkeyAcceptedKeyTypes +ssh-rsa                                                                                         
                                                                                                                        
                                                                                                                        
Match User root                                                                                                         
    PasswordAuthentication yes